name: Build Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #- uses: browser-actions/setup-geckodriver@latest
    #- uses: browser-actions/setup-firefox@v1

    #- run: geckodriver --version
    #- run: firefox --version

    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
        cache: maven

    - name: Maven Install
      run: mvn -Dmaven.test.skip=true clean install --batch-mode
    - name: Maven tests
      run: mvn -Djava.awt.headless=true -Dmaven.test.redirectTestOutputToFile=true --fail-at-end --batch-mode org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report
      # run: mvn -T 1C -Djava.awt.headless=true -Dmaven.test.redirectTestOutputToFile=true --fail-at-end --batch-mode org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report install

    - name: Codecov
      uses: codecov/codecov-action@v3.1.1

